export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_FAILED = 'SEARCH_ARTIST_FAILED';

export const GET_ARTIST_INFO_REQUEST = 'GET_ARTIST_INFO_REQUEST';
export const GET_ARTIST_INFO_SUCCESS = 'GET_ARTIST_INFO_SUCCESS';
export const GET_ARTIST_INFO_FAILED = 'GET_ARTIST_INFO_FAILED';

export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
